### ISSUE TITLE
SMACC Viewer License 

### ISSUE THREAD

**Issue by odarwish2022** [robosoft-ai/SMACC#58]
Hello,

This is not really an issue but a question regarding the license of the SMACC viewer. Sorry if this is not the appropriate place to post this question but I really couldn't find anywhere else:

The SMACC Viewer's license agreement mentions that a license may be purchased in the case of commercial use, can I please get more information regarding this?

Regards,
Omar

┆Issue is synchronized with this [Jira Task](https://robosoft-ai.atlassian.net/browse/SMACC1-2) by [Unito](https://www.unito.io)
┆Link To Issue: https://robosoft-ai.atlassian.net/browse/SMACC1-2

**Comment by brettpac** [comment]
Hi @odarwish2022 
After going back and forth internally on this one, we finally decided that its time to retire the SMACC Viewer.

But we backported the SMACC Run-Time Analyzer to ROS1, and you can find it [here](https://robosoft.ai/product-category/smacc1-runtime-analyzer/), with installation instructions [here](https://robosoft.ai/smacc1_rta-installation/).
Its free for academic and personal use, and commercial licenses are based on the number of employees within the organization. Information regarding license criteria is found on each product page. For instance [here](https://robosoft.ai/product/smacc1-rta-small-business-license/) is the small business version for companies with 10-50 employees.

Please let us know if you have any more questions.
